name: vibration_timer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




  cupertino_icons: ^1.0.2
  vibration: ^1.7.4-nullsafety.0
  freezed:
  flutter_state_notifier:
  state_notifier:
  build_runner:

  #timer
  timer_count_down: ^2.2.0

  #通知
  flutter_local_notifications: ^8.2.0

  #言語選択
  flutter_cupertino_localizations:

  #importを整理
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true